-- MySQL Script generated by MySQL Workbench
-- Tuesday 10 October 2017 04:15:24 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecommerce` ;

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8 ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`supplier` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`supplier` (
  `supplier_id` INT NOT NULL AUTO_INCREMENT,
  `supplier_name` VARCHAR(45) NOT NULL,
  `supplier_contact` DECIMAL(10) NULL,
  PRIMARY KEY (`supplier_id`))
ENGINE = InnoDB
COMMENT = 'Strong Entity';


-- -----------------------------------------------------
-- Table `ecommerce`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`customer` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(45) NOT NULL,
  `customer_contact` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB
COMMENT = 'Strong Entity';


-- -----------------------------------------------------
-- Table `ecommerce`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`order` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `order_amount` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `time` DATETIME NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_customer_idx` (`customer_id` ASC),
  UNIQUE INDEX `customer_time_Unique` (`customer_id` ASC, `time` ASC),
  CONSTRAINT `fk_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `ecommerce`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Weak Entity';


-- -----------------------------------------------------
-- Table `ecommerce`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`items` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`items` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `item_name` VARCHAR(45) NOT NULL,
  `item_cost` INT NOT NULL,
  `supplier_id` INT NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_Items_Supplier1_idx` (`supplier_id` ASC),
  CONSTRAINT `fk_Items_Supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `ecommerce`.`supplier` (`supplier_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Weak Entity';


-- -----------------------------------------------------
-- Table `ecommerce`.`order_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`order_items` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`order_items` (
  `order_id` INT NOT NULL,
  `items_id` INT NOT NULL,
  PRIMARY KEY (`order_id`, `items_id`),
  INDEX `fk_items_idx` (`items_id` ASC),
  CONSTRAINT `fk_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `ecommerce`.`order` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_items`
    FOREIGN KEY (`items_id`)
    REFERENCES `ecommerce`.`items` (`item_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
