-- MySQL Script generated by MySQL Workbench
-- Tuesday 10 October 2017 08:48:55 AM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ProjectsEmployeesSchema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ProjectsEmployeesSchema` ;

-- -----------------------------------------------------
-- Schema ProjectsEmployeesSchema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjectsEmployeesSchema` DEFAULT CHARACTER SET utf8 ;
USE `ProjectsEmployeesSchema` ;

-- -----------------------------------------------------
-- Table `ProjectsEmployeesSchema`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectsEmployeesSchema`.`employees` ;

CREATE TABLE IF NOT EXISTS `ProjectsEmployeesSchema`.`employees` (
  `employee_id` DECIMAL(10) NOT NULL,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `designation` VARCHAR(30) NOT NULL,
  `salary` INT NOT NULL DEFAULT 0,
  `contact_no` DECIMAL(10) NOT NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB
COMMENT = 'Strong Entity';


-- -----------------------------------------------------
-- Table `ProjectsEmployeesSchema`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectsEmployeesSchema`.`projects` ;

CREATE TABLE IF NOT EXISTS `ProjectsEmployeesSchema`.`projects` (
  `project_id` DECIMAL(10) NOT NULL,
  `project_title` VARCHAR(45) NOT NULL,
  `project_desc` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`project_id`))
ENGINE = InnoDB
COMMENT = 'Weak Entity';


-- -----------------------------------------------------
-- Table `ProjectsEmployeesSchema`.`employee_manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectsEmployeesSchema`.`employee_manager` ;

CREATE TABLE IF NOT EXISTS `ProjectsEmployeesSchema`.`employee_manager` (
  `employee_id` DECIMAL(10) NOT NULL,
  `manager_id` DECIMAL(10) NOT NULL,
  INDEX `fk_employee_manager_2_idx` (`manager_id` ASC),
  PRIMARY KEY (`employee_id`),
  CONSTRAINT `fk_employee_manager_1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `ProjectsEmployeesSchema`.`employees` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_employee_manager_2`
    FOREIGN KEY (`manager_id`)
    REFERENCES `ProjectsEmployeesSchema`.`employees` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectsEmployeesSchema`.`employee_project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectsEmployeesSchema`.`employee_project` ;

CREATE TABLE IF NOT EXISTS `ProjectsEmployeesSchema`.`employee_project` (
  `employee_id` DECIMAL(10) NOT NULL,
  `project_id` DECIMAL(10) NOT NULL,
  INDEX `fk_employee_project_2_idx` (`project_id` ASC),
  PRIMARY KEY (`employee_id`),
  CONSTRAINT `fk_employee_project_1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `ProjectsEmployeesSchema`.`employees` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_project_2`
    FOREIGN KEY (`project_id`)
    REFERENCES `ProjectsEmployeesSchema`.`projects` (`project_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
