-- MySQL Script generated by MySQL Workbench
-- Tuesday 10 October 2017 12:27:23 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema FoodDelivery
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `FoodDelivery` ;

-- -----------------------------------------------------
-- Schema FoodDelivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FoodDelivery` DEFAULT CHARACTER SET utf8 ;
USE `FoodDelivery` ;

-- -----------------------------------------------------
-- Table `FoodDelivery`.`restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FoodDelivery`.`restaurant` ;

CREATE TABLE IF NOT EXISTS `FoodDelivery`.`restaurant` (
  `restaurant_id` INT NOT NULL AUTO_INCREMENT,
  `restaurant_name` VARCHAR(45) NOT NULL,
  `contact` DECIMAL(10) NOT NULL,
  `address` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`restaurant_id`))
ENGINE = InnoDB
COMMENT = 'Strong Entity';


-- -----------------------------------------------------
-- Table `FoodDelivery`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FoodDelivery`.`customer` ;

CREATE TABLE IF NOT EXISTS `FoodDelivery`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `contact_no` DECIMAL(10) NOT NULL,
  `address` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `contact_no_UNIQUE` (`contact_no` ASC))
ENGINE = InnoDB
COMMENT = 'Strong Entity';


-- -----------------------------------------------------
-- Table `FoodDelivery`.`delivery_person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FoodDelivery`.`delivery_person` ;

CREATE TABLE IF NOT EXISTS `FoodDelivery`.`delivery_person` (
  `person_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `contact` DECIMAL(10) NOT NULL,
  PRIMARY KEY (`person_id`),
  UNIQUE INDEX `contact_UNIQUE` (`contact` ASC))
ENGINE = InnoDB
COMMENT = 'Strong Entity';


-- -----------------------------------------------------
-- Table `FoodDelivery`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FoodDelivery`.`order` ;

CREATE TABLE IF NOT EXISTS `FoodDelivery`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `delivery_person_id` INT NOT NULL,
  `restaurant_id` INT NOT NULL,
  `order_placing_time` DATETIME NOT NULL,
  `order_delivery_time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_Order_Customer1_idx` (`customer_id` ASC),
  INDEX `fk_Order_DeliveryPerson1_idx` (`delivery_person_id` ASC),
  INDEX `fk_Order_Restaurant1_idx` (`restaurant_id` ASC),
  UNIQUE INDEX `customer_time_Unique` (`customer_id` ASC, `order_placing_time` ASC),
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `FoodDelivery`.`customer` (`customer_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Order_DeliveryPerson1`
    FOREIGN KEY (`delivery_person_id`)
    REFERENCES `FoodDelivery`.`delivery_person` (`person_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Order_Restaurant1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `FoodDelivery`.`restaurant` (`restaurant_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Weak Entity';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
