-- MySQL Script generated by MySQL Workbench
-- Tuesday 10 October 2017 05:38:58 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Paytm
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Paytm` ;

-- -----------------------------------------------------
-- Schema Paytm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Paytm` DEFAULT CHARACTER SET utf8 ;
USE `Paytm` ;

-- -----------------------------------------------------
-- Table `Paytm`.`branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Paytm`.`branch` ;

CREATE TABLE IF NOT EXISTS `Paytm`.`branch` (
  `branch_id` INT NOT NULL AUTO_INCREMENT,
  `branch_name` VARCHAR(45) NOT NULL,
  `branch_ifsc` VARCHAR(12) NOT NULL,
  `branch_address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`branch_id`),
  UNIQUE INDEX `branch_ifsc_UNIQUE` (`branch_ifsc` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Paytm`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Paytm`.`account` ;

CREATE TABLE IF NOT EXISTS `Paytm`.`account` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `account_type` VARCHAR(15) NOT NULL,
  `account_balance` DECIMAL NOT NULL,
  `branch_id` INT NOT NULL,
  PRIMARY KEY (`account_id`),
  INDEX `fk_branch_idx` (`branch_id` ASC),
  UNIQUE INDEX `customer_branch_Unique` (`customer_id` ASC, `branch_id` ASC),
  CONSTRAINT `fk_branch`
    FOREIGN KEY (`branch_id`)
    REFERENCES `Paytm`.`branch` (`branch_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Paytm`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Paytm`.`customer` ;

CREATE TABLE IF NOT EXISTS `Paytm`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `aadhar_no` VARCHAR(45) NOT NULL,
  `contact_no` DECIMAL(10) NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Paytm`.`customer_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Paytm`.`customer_account` ;

CREATE TABLE IF NOT EXISTS `Paytm`.`customer_account` (
  `customer_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`, `branch_id`),
  INDEX `fk_account_idx` (`account_id` ASC),
  INDEX `fk_branch_idx` (`branch_id` ASC),
  CONSTRAINT `fk_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `Paytm`.`customer` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `Paytm`.`account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_branch`
    FOREIGN KEY (`branch_id`)
    REFERENCES `Paytm`.`account` (`branch_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
